<?php
error_reporting(ALL);
include '../../../controllers/cont.main.php';
function errorHandler($errno, $errstr, $errfile, $errline) {
	// In this script, the silently suppress any error generated by getimagesize
	// which will throw an error if the "image" isn't an image
	// ie doesn't have a valid width / height

	/* Don't execute PHP internal error handler */
	return true;
}

$old_error_handler = set_error_handler("errorHandler");

function isImage($tempFile) {

	// Get the size of the image
	$size = getimagesize($tempFile);

	if (isset($size) && $size[0] && $size[1] && $size[0] *  $size[1] > 0) {
		return true;
	} else {
		return false;
	}
}
function generate_string($strength = 16) {
	$input = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
	$input_length = strlen($input);
	$random_string = '';
	for($i = 0; $i < $strength; $i++) {
		$random_character = $input[mt_rand(0, $input_length - 1)];
		$random_string .= $random_character;
	}
	return $random_string;
}

if (!empty($_FILES)) {

	$fileData = $_FILES['Filedata'];
	$finalArray = array('success' => 0, 'url' => null);
	if ($fileData) {
		$folder = '../uploads/manga/'.(int)$_POST['mid'].'/';
		$folder2 = '../uploads/manga/'.$_POST['url'].'/';
		if (!is_dir($folder)) { 
			mkdir($folder, 0775, true);
		}
		if (!is_dir($folder2)) {
			mkdir($folder2, 0775, true);
		}
		$fileParts = pathinfo($fileData['name']);
		$tempFile   = $fileData['tmp_name'];
		$targetFile = $folder2.generate_string(20).$fileParts['basename'];
		// Validate the file type
		$fileTypes = array('jpg', 'jpeg', 'gif', 'png', 'webp'); // Allowed file extensions
		
		if (in_array(strtolower($fileParts['extension']), $fileTypes) && filesize($tempFile) > 0 && isImage($tempFile)) {
			if (move_uploaded_file($tempFile, $targetFile)) {
				$finalImg = '/app/manga/'.substr($targetFile."\xA", 3);
				$finalArray['success'] = 1;
				$finalArray['url'] = $finalImg;
			}
		}
		$json = json_encode($finalArray);
		echo $json;
	}
	
}